---
name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2022]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: npm cache clean –force && node ./script/build-current-platform.js
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.blockmap
            dist/*.yml
            dist/*.deb
            dist/*.rpm
